### ISSUE TITLE
[PE-D] "find sushi | rice" does not return the sushi recipe even though one of its ingredients is rice

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-T17-2/tp#195] opened 2022-04-01 16:44 UTC
Problem as stated in the title. Even if this is intended it would be a lot clearer if you could specify what attributes are searched. What I could gather from the user guide is that tags and ingredients are also searched but apparently that's not the case considering this bug.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: DaneMarc/ped#3

**Comment by yusufaine** [comment] 2022-04-03 04:31
Duplicate of #190.

**Closed by yusufaine** 2022-04-03 04:31 UTC
